token: ""
debug: false
privileged-gateway-intents:
  presence: false
  server-members: false
  message-content: false
cache:
  enabled:
    #- "ACTIVITY" # Need Presence Privilege Intent
    #- "CLIENT_STATUS" # Need Presence Privilege Intent
    #- "ONLINE_STATUS" # Need Presence Privilege Intent
    - "EMOJI"
    - "FORUM_TAGS"
    - "MEMBER_OVERRIDES"
    - "ROLE_TAGS"
    - "SCHEDULED_EVENTS"
    - "SOUNDBOARD_SOUNDS"
    - "STICKER"
    - "VOICE_STATE"
mongodb:
  enabled: false
  uri: ""
redis:
  enabled: false
  uri: ""
lavalink:
  enabled: false
commands:
  slash:
    enabled: true
    register: "Local" #Global or Local (Everything other than those 2 terms will be seen as Local)
  disabled: #Excluded Registered Commands
    - ""